#include <stdio.h>
#include <math.h>

int i, j, a, b, pos=0;
double ans;
double terms[10000] = {0.0};

main(){

    for(a=2; a<=100; a++){
        for(b=2; b<=100; b++){

            int eq = 1;
            i=1;

            double x=(double)a;
            double y=(double)b;
            ans = pow(x, y); // calculate x^y

            for(j=0; j<10000; j++){

                while(terms[j]==ans){ // check whether ans has been calculated before
                    eq = 0;
                    break;
                }
            }

            if(eq==1){ // if ans is not in the array, it is saved to the array
                terms[pos] = ans;
                pos++; // count the no. of distinct terms
            }
        }
    }

printf("No. of distinct terms in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100 = %d\n", pos);
// pos = 9183

}

